### ISSUE TITLE
How do you finetune your deep homography network?

### ISSUE THREAD

**Issue by breadcake** [nie-lang/UnsupervisedDeepImageStitching#1]
Hello! In your paper, you first train your deep homography network on Stitched MSCOCO and then finetune it on your real dataset. But the two datasets have different resolution of about 128×128 and 512×512 respectively, while the homography network may not handle different input size since it has fully connected layers. So I wonder what's the input size of your deep homography network and how do you finetune it? Thank you！

**Comment by nie-lang** [comment]
Hi, we just resize our real dataset from 512×512 to 128×128 when we finetune our homography network on the proposed real dataset.

To make our deep stitching framework can handle images of arbitrary resolutions, we regress the eight offsets of the four vertices on the resolution of 128×128 and solve the homography matrix on the resolution of the original resolution (e.g. 512×512). The details can be found in the Section Ⅲ(C) of "Learning Edge-Preserved Image Stitching from
Large-Baseline Deep Homography" (https://arxiv.org/pdf/2012.06194.pdf).

**Comment by breadcake** [comment]
Thank you for your reply!
