### ISSUE TITLE
Why Seam mask is derived from such formula?

### ISSUE THREAD

**Issue by DanilHu** [nie-lang/UnsupervisedDeepImageStitching#24]
Hi, I encountered a problem when reading the seam loss part. 
![image](https://user-images.githubusercontent.com/40864036/158505672-b8763f64-035b-477e-9668-00363f2e24a3.png)
Could you please tell me why this `M^{AS}` can be calculated like this? 
1. What is the physical significance of `\nabla M^{AC}`(I mean this is not like general edge ectraction which obtain the object edge from a image, here is just the all one mask)?
2.  And what is the meaning of these convolutions with $E_{33}$? 
3. What `M^{AS}` really mean?

**Comment by nie-lang** [comment]
1. \nabla M^{AC} is the edge extracted from the content mask M^{AC}. (Refer to Fig. 6 of the paper.)
2. The convolutions with fixed all-one kernels could expand the width of the edges. It's like an operation of dilating. It makes the edges more clear.
3. M^{AS} is the one-zero mask illustrated in Fig. 6. M^{AS} and M^{BS} indicate the edges of the overlapping regions.

**Comment by DanilHu** [comment]
Ok, thanks, Got it! It actually is the overlapping regions boundary right?

**Comment by nie-lang** [comment]
Yes.
