### ISSUE TITLE
loss issue

### ISSUE THREAD

**Issue by Scott-che** [nie-lang/UnsupervisedDeepImageStitching#47]
![Capture](https://user-images.githubusercontent.com/67545227/190640853-268bab81-50a6-445c-b9c2-081814a5e8f6.PNG)
目前照著github上的指示後，執行train_H.py，只修改batch_size為1，看loss似乎沒有收斂的跡象，想問問是哪裡出了問題嗎?

**Comment by Scott-che** [comment]
![Capture](https://user-images.githubusercontent.com/67545227/190666277-7324c64b-ac4e-400d-9175-bd31731a8b82.PNG)
![1](https://user-images.githubusercontent.com/67545227/190666604-98322390-8b4d-45ca-8d60-e82f8e4f9aff.PNG)
結果大概在step到20340 loss就出現nan了，請問這有方法可以解決嗎

**Comment by nie-lang** [comment]
我训练的时候是没有出现nan的，但根据反馈好多人都出现了。我怀疑有一部分是环境原因。

更常规的做法是替换cost volume层为其他的操作，比如concat或ccl （可参考我tcsvt的另一个人开源项目），根据反馈，性能会变化，但训练会更稳定。

还可以尝试下一个pytorch的复现版 UnsupDIS-pytorch。
