### ISSUE TITLE
Learning edge-preserved image stitching from multi-scale deep homography

### ISSUE THREAD

**Issue by Scott-che** [nie-lang/UnsupervisedDeepImageStitching#48]
你好，我正在閱讀Learning edge-preserved image stitching from multi-scale deep homography，想請問ground truth offsets是怎麼來的?
![Capture](https://user-images.githubusercontent.com/67545227/192971100-8a49fa0b-a586-437d-ad1e-254eb93bc4d1.PNG)

**Comment by nie-lang** [comment]
这是he成数据集，gt offsets可参考https://github.com/nie-lang/DeepImageStitching-1.0/blob/main/Dataset_gen/dataset.py

如果我没记错的话，在这篇论文中，我好像没有把分辨率固定到128*128，不过最后跑出来的效果好像和128*128的差不多

**Comment by Scott-che** [comment]
![Capture](https://user-images.githubusercontent.com/67545227/192984390-f2ca77a7-1255-4e35-8a5e-040634fad599.PNG)
了解，謝謝回覆，另外想請問這個ground truth是怎麼獲得的

**Comment by nie-lang** [comment]
也可以通过这个代码获得，不过实际的label有周围的无效像素区域，论文中为了美观把这部分区域裁剪掉了

**Comment by Scott-che** [comment]
也可以通过这个代码获得: 是指執行這篇UnsupervisedDeepImageStitching reconstruction的interence.py所獲得的拼接圖像嗎?

因為我目前在看這條式子，不太清楚I_hat和I指的指哪邊
![Capture](https://user-images.githubusercontent.com/67545227/192989410-f35d86f4-09ec-4cef-90b4-79a5fc7760b0.PNG)
![Capture](https://user-images.githubusercontent.com/67545227/192989516-4e73784b-f252-4429-95b4-b785f487f2b2.PNG)

**Comment by nie-lang** [comment]
1. 不是。是合成数据集拼接图的gt可以通过那个代码获得
2. 合成数据集上拼接图和拼接图的gt

**Comment by Scott-che** [comment]
那個代碼指的是https://github.com/nie-lang/DeepImageStitching-1.0/blob/main/Dataset_gen/dataset.py ?

**Comment by Scott-che** [comment]
謝謝你用心地回覆
