### ISSUE TITLE
solve DTL

### ISSUE THREAD

**Issue by Scott-che** [nie-lang/UnsupervisedDeepImageStitching#49]
![Capture](https://user-images.githubusercontent.com/67545227/193725362-26d17b15-9d53-408b-865a-e4bb58cea7bb.PNG)
你好，想詢問在經過solve DLT後得到的H1為什麼不是直接拿這個H1去對圖像做warp，而是又經過西些處理得到新的H1後，才對圖像warp，有點看不太懂中間M的部分

**Comment by nie-lang** [comment]
你好，经过M矩阵相关运算后，DLT算法可以被视为normalized DLT算法，在传统的多视几何解法中，normalized DLT往往精度更高
更多细节可参考 issue 10(https://github.com/nie-lang/UnsupervisedDeepImageStitching/issues/10)
