### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lhy121** [nie-lang/UnsupervisedDeepImageStitching#5]
你好，在运行ImageAlignment/Codes/inference.py时遇到了如下错误：
image = np_load_frame(data_info_list[i]['frame'][index], resize_height, resize_width)
IndexError: list index out of range
self.datas = OrderedDict()这个赋值好像是空
![捕获](https://user-images.githubusercontent.com/92787003/137886043-840f95b4-b233-471e-aabe-b98ed3bfba93.JPG)
值

**Comment by lhy121** [comment]
![捕获](https://user-images.githubusercontent.com/92787003/137894333-049646f6-f0c1-49e2-b345-42236d1bb7d0.JPG)应该没有错

**Comment by nie-lang** [comment]
应该是windows系统下路径的问题，我刚刚试了，在windows环境下需要把下图所示这个地方‘/’改成‘\\’
![1](https://user-images.githubusercontent.com/54256137/137901102-eafc5f95-9830-4f86-8db0-cc62966deee4.png)
