### ISSUE TITLE
multiple image stitching

### ISSUE THREAD

**Issue by Scott-che** [nie-lang/UnsupervisedDeepImageStitching#50]
聶博士您好，
我目前也剛開始研究圖像拼接這領域，目前網上的資料及拼接方法都是以兩張為主，想請問您在這多張拼接圖像方面有何建議。

**Comment by nie-lang** [comment]
多图拼接更多的是工程问题，比如两两图片估计homo后如何将所有图片放置在同一画布内。而从更学术的角度来看，研究两张图的拼接就够了，所以现在大部分资料都是以两张图为主。

**Comment by qazzombie** [comment]
> 多图拼接更多的是工程问题，比如两两图片估计homo后如何将所有图片放置在同一画布内。而从更学术的角度来看，研究两张图的拼接就够了，所以现在大部分资料都是以两张图为主。

你好，请问能推荐一下对于多张图拼接的工程实现项目吗，感觉基于深度学习的有点摸不着头脑
