### ISSUE TITLE
模型使用问题

### ISSUE THREAD

**Issue by lhy121** [nie-lang/UnsupervisedDeepImageStitching#8]
怎么将自己训练的模型放入inference.py和output_inference.py中使用，作者的checkpoint模型的模型文件格式是
.data-00000-of-00001，.index和.meta。但我训练出来的模型在summary文件夹里是.LAPTOP-B63M1QTF，在inference.py中修改snapshot_dir路径成SUMMARY_DIR+'events.out.tfevents.1636531600.LAPTOP-B63M1QTF'会报错

**Comment by nie-lang** [comment]
训练出来的模型应该会保存到snapshot_dir变量定义的目录下，summary中是训练过程中tensorboard的可视化的日志文件

**Comment by lhy121** [comment]
好的，谢谢
